const GET_USER="GET_USER";
const USER_SUCCESS="USER_SUCCESS";
const USER_FAILED="USER_FAILED";
const GET_ORDERS="GET_ORDERS";
const ORDERS_SUCCESS="ORDERS_SUCCESS";
const ORDERS_FAILED="ORDERS_FAILED";
const SIGN_OUT="SIGN_OUT";


export {GET_USER,USER_SUCCESS,USER_FAILED,ORDERS_SUCCESS,ORDERS_FAILED,GET_ORDERS,SIGN_OUT};